apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.appConfig.appName }}
  labels:
    app: {{ .Values.db.appConfig.appName }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.db.appConfig.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.appConfig.appName }}
    spec:
      containers:
        - name: {{ .Values.db.appConfig.appName }}-container
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-eitan
                  key: post-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-eitan
                  key: post-pass
            - name: POSTGRES_DB
              value: "mydatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: {{ .Values.db.appConfig.appName }}
  type: {{ .Values.db.service.type }}
  ports:
    - protocol: {{ .Values.db.service.protocol }}
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
