apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
spec:
  project: default

  sources:
    repoURL: https://github.com/EITANPOD/simple-argocd-chart.git
    targetRevision: HEAD
    path: /simple-chart-argocd
    helm:
      valueFiles:
      - /simple-chart-argocd/custom-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: eitan-argocd-prac

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:  
      - CreateNamespace=true 
